name: Adventure-Afk
main: com.caved_in.adventurecraft.afk.AdventureAfk
version: ${project.version}
description: Run away from your keyboard without fear of getting diced!
author: Brandon Curtis
depend: [Commons]
commands:
   afk:
      description: Simply go AFK!
      usage: /<command>