name: Adventure-Items
main: com.caved_in.adventurecraft.adventureitems.AdventureItems
version: ${project.version}
description: Epic Sexy RPG Itemness
author: Brandon Curtis
depend: [Commons,Adventure-Loot]
commands:
   adventureitems:
      description: The adventure fishing command helps admins expand the loot and tweak config for the fishing events.
      usage: /<command>