name: Adventure-Skills
main: com.caved_in.adventurecraft.skills.AdventureSkills
version: ${project.version}
description: The best Skills Plugin Evar!
author: MumbosHut
depend: [Commons,Entity-Mechanic]
softdepend: [BossBarAPI]
commands:
   skills:
      description: Access and manage your skills.
      usage: /<command>

