name: Adventure-Shop
main: com.caved_in.adventurecraft.shop.AdventureShop
version: ${project.version}
description: Loot for all and gold for some!
author: Brandon Curtis
depend: [Commons]
commands:
   shop:
      description: Used to aid administration of the shop.
      usage: /<command>