name: Adventure-Loot
main: com.devsteady.loot.AdventureLoot
version: 1.3.0
description: When even your loot is full of adventure you know it's a good time!
author: Brandon Curtis
depend: [Commons]
softdepend: [Shards]
commands:
   loot:
      description: The main command, used to handle all the aspects of the loot plugin.
      usage: /<command>