name: Adventure-Core
main: com.caved_in.adventurecraft.core.AdventureCore
version: ${project.version}
description: The mother-ship to all the custom plugins and features for adventure craft!
author: Brandon Curtis
depend: [Commons,Adventure-Gems]
softdepend: [Adventure-Homes,Vault,Towny]
commands:
   adventure:
      description: The adventure command is used by admins to help build and make adventures around the world!
      usage: /<command>
   exchange:
      description: Convert your Tunnels EXP into Gold for Adventure Craft, and vice versa!
      usage: /<command> <gold/exp>